
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: audisped-backend:latest
    ports:
      - "15435:15435"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: audisped-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
